### ISSUE TITLE
广告可以去了吗？图片好像只可以上传2张？

### ISSUE THREAD

**Issue by oemsys** [xiaoxinpro/xxjzWeChat#5]
![image](https://user-images.githubusercontent.com/32034317/83216801-bad96180-a19c-11ea-847c-d41202949659.png)

![image](https://user-images.githubusercontent.com/32034317/83216928-ff64fd00-a19c-11ea-821b-e025edbb9d04.png)
![image](https://user-images.githubusercontent.com/32034317/83216950-0ab82880-a19d-11ea-9df4-20accac3db71.png)

**Comment by xiaoxinpro** [comment]
1、广告需要手动删除全部广告代码，可以全局检索`unit-id`，逐个删除。
2、上传图片限制可以修改`/app.js`文件中的`ImageConfig.freeCount`的值。

**Comment by oemsys** [comment]
WEB可以传图片，可以预览图片，微信小程序里不行，是不是哪边还要修改 ？

**Comment by xiaoxinpro** [comment]
请提供一下小程序里面的报错信息

**Comment by oemsys** [comment]
![image](https://user-images.githubusercontent.com/32034317/83220691-4e636000-a1a6-11ea-9fa6-db7f0dffa60b.png)

**Comment by xiaoxinpro** [comment]
在`/utils/image.js`文件中下图位置插入调试代码`console.log(res);`，再看一下调试信息。

![image](https://user-images.githubusercontent.com/11443745/83221524-9e432680-a1a8-11ea-83a3-39dfea2c4149.png)

**Comment by oemsys** [comment]
![image](https://user-images.githubusercontent.com/32034317/83221910-be271a00-a1a9-11ea-9544-39aeda01b850.png)
![image](https://user-images.githubusercontent.com/32034317/83221993-e7e04100-a1a9-11ea-8441-0a05872af7ea.png)
好了~！非常感谢。还有那个多人可编辑一个帐本这个怎么搞？

**Comment by xiaoxinpro** [comment]
不客气

多人编辑一个账本目前无解，如果你从事开发工作可以考虑将数据库user从account...表中剥离，增加一个group表代替原uid字段，再构建一个user与group匹配的逻辑。

希望可以帮到你！
