### ISSUE TITLE
为什么我获取不了微信头像

### ISSUE THREAD

**Issue by ghost** [xiaoxinpro/xxjzWeChat#8]
小歆记账怎么改，还有为什么我获取不了微信头像

**Comment by ghost** [comment]
找到改的地方了，但是微信头像还是获取不了？？

**Comment by ghost** [comment]
哥

**Comment by xiaoxinpro** [comment]
微信需要授权才可以获取到用户信息

**Comment by ghost** [comment]
授权了啊，但是头像还是空白

**Comment by xiaoxinpro** [comment]
请提供错误log

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/43698782/132081144-83e41d8e-cc9b-4ec2-866d-1b3015e47e0a.png)

**Comment by xiaoxinpro** [comment]
这里显示已经获取到头像了，你检查一下[微信小程序开发设置](https://github.com/xiaoxinpro/xxjzWeChat#%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E8%AE%BE%E7%BD%AE)中有没有添加微信头像地址吧。

**Comment by ghost** [comment]
添加了，还是不行

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/43698782/132225930-788ac75a-79b1-481e-9803-5f825f3cc237.png)
